# Author: Zian Huang 
# Date Created: 2025-04-30 
# ---------------------------------------- 

services:
  app:
    # Next.js web application service
    build:
      context: . # Build context directory
      dockerfile: Dockerfile # Dockerfile to use
    labels:
      - "com.example.description=Next.js web application"
      - "com.example.service=web"
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Run with: docker compose up -d --build
# Stop with: docker compose down

# ---------------------------------------- 
# Copyright (c) 2025 Zian Huang. All rights reserved. 
